

    "wxPointShopView/pointExgBeans": "jd_wxPointShop_bean_wxId",
    "daily": "jd_wxDaily_wxId",
    "wxShopFollowActivity": "jd_wxShopFollow_wxId",
    "wxBuildActivity": "jd_wxBuild_wxId",
    "wxKnowledgeActivity": "jd_wxKnowledge_wxId",
    "wx/completeInfoActivity": "jd_wxCompleteInfo_wxId",
    "front/showInviteJoin": "jd_wx_jinggeng_invite_wxId",
    "dingzhi/dz/openCard": "jd_wx_dz_opencard_wxId",
    "categoryUnion/activity": "jd_wx_categoryUnion_opencard_wxId",
    "dingzhi/highRed/active": "jd_wx_highRed_opencard_wxId",
    "dingzhi/joinCommon": "jd_wx_joinCommon_opencard_wxId",
    "dingzhi/customized": "jd_wx_customized_opencard_wxId",
    "dingzhi/shop/league": "jd_wx_shopLeague_opencard_wxId",
    "active/dVF7gQUVKyUcuSsVhuya5d2XD4F": "jd_invite_id",
    "wxCartKoi/cartkoi": "jd_wxCartKoi_wxId",
    "pool/captain": "jd_wxPoolCaptain_join_wxId",
    "wxgame/activity": "jd_wxgame_wxId",
    "wxShareActivity/activity": "jd_wxShare_wxId",
    "wxUnPackingActivity/activity": "jd_wxUnPacking_wxId",
    "mshop/shopdraw": "jd_shopDraw_id",
    "/h5/pages/turntable/turntable?id:": "jd_wx_hdb_draw_wxId",
    "/wxShopGift/activity?activityId": "jd_wxShopGift_wxId",
    "/wxCollectionActivity/activity2": "jd_wxCollection_wxId",
    "/wxDrawActivity/activity?activityId": "jd_wxDraw_wxId",
    "/lzclient/": "jd_wxDraw_wxId",
    "/wx/completeInfoActivity/view/activity?activityId": "jd_wxCompleteInfo_wxId",
    "/mc/wxPointShopView/pointExgShiWu": "jd_wxPointShop_shiwu_wxId",
    "/mc/wxPointShopView/pointExgBeans": "jd_wxPointShop_bean_wxId",
    "/h5/pages/shopGift/customGift": "jd_wx_hdb_shopGift_wxId",
    "/wxInviteActivity/openCard": "jd_wxInvite_wxId",
    "/wxTeam/activity": "jd_wxTeam_wxId",
    "/wxTeam/activity2": "jd_wxTeam_wxId",
    "/mc/wxMcLevelAndBirthGifts/activity": "jd_wxMcLevelAndBirthGifts_wxId",
    "/drawCenter/activity/": "jd_wxDrawCenter_wxId",
    "/wxGameActivity": "jd_wxGameActivity_wxId",
    "hdb-isv.isvjcloud.com/h5/pages/inviteJoin": "jd_wx_hdb_inviteJoin_wxId",
    "wgzsl-isv": "jd_spy_gzsl_game_wxId",

    "daily": "jd_wx_daily",
    "wxShopFollowActivity": "jd_wx_followshop",
    "wxBuildActivity": "jd_wx_build",
    "wxKnowledgeActivity": "jd_wx_Knowledge",
    "wx/completeInfoActivity": "jd_wx_completeInfo",
    "front/showInviteJoin": "jd_jinggeng_showInviteJoin",
    # "dingzhi/dz/openCard": "jd_wx_dz_opencard_wxId",
    # "categoryUnion/activity": "jd_wx_categoryUnion_opencard_wxId",
    # "dingzhi/highRed/active": "jd_wx_highRed_opencard_wxId",
    # "dingzhi/joinCommon": "jd_wx_joinCommon_opencard_wxId",
    # "dingzhi/customized": "jd_wx_customized_opencard_wxId",
    # "dingzhi/shop/league": "jd_wx_shopLeague_opencard_wxId",
    "active/dVF7gQUVKyUcuSsVhuya5d2XD4F": "jd_invite",
    "wxCartKoi/cartkoi": "jd_wx_CartKoi",
    # "pool/captain": "jd_wxPoolCaptain_join_wxId",
    "wxgame/activity": "jd_wx_game",
    "wxShareActivity/activity": "jd_wx_share",
    "wxUnPackingActivity/activity": "jd_wx_UnPacking",
    # "mshop/shopdraw": "jd_shopDraw_id",
    "/h5/pages/turntable/turntable?id:": "jd_hdb_draw",
    "/wxShopGift/activity": "jd_daily_follow",
    "/wxCollectionActivity": "jd_wx_collection",
    "/wxDrawActivity/": "jd_wx_draw",
    "/lzclient/": "jd_wx_draw",
    # "/wx/completeInfoActivity/view/activity?activityId": "jd_wx_completeInfo",
    # "/mc/wxPointShopView/pointExgShiWu": "jd_wxPointShop_shiwu_wxId",
    # "/mc/wxPointShopView/pointExgBeans": "jd_wxPointShop_bean_wxId",
    # "/h5/pages/shopGift/customGift": "jd_wx_hdb_shopGift_wxId",
    "/wxInviteActivity/openCard": "jd_wx_invite_opencard",
    "/wxTeam/activity": "jd_wx_team",
    "/mc/wxMcLevelAndBirthGifts/activity": "jd_wx_McLevelAndBirthGifts",
    "/drawCenter/activity/": "jd_wx_drawCenter",
    "/wxGameActivity": "jd_wx_gameActivity",
    "hdb-isv.isvjcloud.com/h5/pages/inviteJoin": "jd_jinggeng_showInviteJoin",
    "activityType=10032": "jd_lz_collectCard",
    "activityType=10024": "jd_lz_collection",
    "activityType=10020": "jd_lz_draw",
    "activityType=10021": "jd_lz_draw",
    "activityType=10062": "jd_lz_draw",
    "activityType=10079": "jd_lz_exchange",
    "activityType=10053": "jd_lz_followGoods",
    "activityType=10068": "jd_lz_followShop",
    "activityType=10089": "jd_lz_game",
    "activityType=10082": "jd_lz_game",
    "activityType=10095": "jd_lz_game",
    "activityType=10070": "jd_lz_invite",
    "activityType=10069": "jd_lz_lkFollowShop",
    "activityType=10035": "jd_lz_second",
    "activityType=10043": "jd_lz_share",
    "activityType=10023": "jd_lz_sign",
    "jinggengjcq-isv.isvjcloud.com/jdbeverage/pages": "jd_mpdz_BigAlliance_opencard",
#    "lives.jd.com": "jd_daily_live",
#    "/live.html?": "jd_daily_live",